/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Session: () => import('#controllers/session_controller'),
  SignUp: () => import('#controllers/sign_up_controller'),
}
