/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  auth: {
    Session: () => import('#controllers/auth/session_controller'),
    SignUp: () => import('#controllers/auth/sign_up_controller'),
  },
  Drink: () => import('#controllers/drink_controller'),
  Family: () => import('#controllers/family_controller'),
  Page: () => import('#controllers/page_controller'),
}
