/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  admin: {
    Characters: () => import('#controllers/admin/characters_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
  },
  auth: {
    Session: () => import('#controllers/auth/session_controller'),
    SignUp: () => import('#controllers/auth/sign_up_controller'),
  },
  Bottles: () => import('#controllers/bottles_controller'),
  Characters: () => import('#controllers/characters_controller'),
  Drink: () => import('#controllers/drink_controller'),
  Family: () => import('#controllers/family_controller'),
  Home: () => import('#controllers/home_controller'),
  Issues: () => import('#controllers/issues_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Stats: () => import('#controllers/stats_controller'),
}
