/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CacheSchema extends BaseModel {
  static $columns = ['expiresAt', 'key', 'value'] as const
  $columns = CacheSchema.$columns
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: string | null
}

export class CharacterSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'image', 'name', 'updatedAt'] as const
  $columns = CharacterSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: any | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DrinkLogSchema extends BaseModel {
  static $columns = ['amountMl', 'createdAt', 'drinkId', 'id', 'updatedAt'] as const
  $columns = DrinkLogSchema.$columns
  @column()
  declare amountMl: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare drinkId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DrinkSchema extends BaseModel {
  static $columns = ['createdAt', 'drinkDate', 'id', 'milliliter', 'updatedAt', 'userId'] as const
  $columns = DrinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare drinkDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare milliliter: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class FamilySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ownerId', 'slug', 'updatedAt'] as const
  $columns = FamilySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ownerId: number
  @column()
  declare slug: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IssueSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'report', 'status', 'updatedAt', 'userId'] as const
  $columns = IssueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare report: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'birthdate', 'characterId', 'climate', 'createdAt', 'dayEnd', 'dayStart', 'email', 'familyId', 'gender', 'height', 'id', 'intervalMinutes', 'milliliterTarget', 'name', 'password', 'streak', 'streakStart', 'updatedAt', 'weight', 'workType'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: any | null
  @column.date()
  declare birthdate: DateTime
  @column()
  declare characterId: number | null
  @column()
  declare climate: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayEnd: string
  @column()
  declare dayStart: string
  @column()
  declare email: string
  @column()
  declare familyId: number | null
  @column()
  declare gender: string
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare intervalMinutes: number
  @column()
  declare milliliterTarget: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare streak: number
  @column.date()
  declare streakStart: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: number
  @column()
  declare workType: string
}
